services:
  - type: web
    name: deploykit-api
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS
        value: http://0.0.0.0:80
      - key: ConnectionStrings__Sqlite
        value: Data Source=/data/deploykit.db
      - key: AdminKey
        value: admin
    disk:
      name: data
      mountPath: /data
      sizeGB: 1
